### ISSUE TITLE
Host should automatically serve any libraries in `out/`

### ISSUE THREAD

**Issue by jkomoros** [dglazkov/polymath#19]
Currently the server needs to have a specific file specified in `LIBRARY_FILENAME`. That's nice if, during development, you have a number of different libraries in your out folder but only want a given server to host one. But you also have to remember to provide the library name.

If the library name isn't provided as an environment variable, it should `load_default_libraries()` to get all of them.

Also, `out/` should be renamed to `data/` or `libraries/` or something.

**Comment by dglazkov** [comment]
👍🏻 to `libraries/`
