### ISSUE TITLE
Ensure that the HTML at endpoints is clear

### ISSUE THREAD

**Issue by jkomoros** [dglazkov/polymath#45]
Right now if someone doesn't know how to use polymath, and someone says "My endpoint is at https://polymath.komoroske.com", the default thing to do is visit it. But right now you get a confusing form without explanation about what to do. In reality very very few people will interact with an endpoint directly, and this (accidental) first interaction is a point of friction for people new to polymath.

We should clean up the HTML from those endpoints to maximize clarity for users to find themselves there.

**Comment by dglazkov** [comment]
I have a crazy idea. I am going to build a tiny web app that acts as a simple endpoint client. And we serve it as the default HTML.

**Comment by jkomoros** [comment]
Yeah I love that. As in, it serves the content from #41.

One downside is that the host then has to implicitly allow access to their OPENAI_API_KEY (or I guess it could open a little dialog that says "Paste your Openai_key here, it won't be transmitted except to OpenAI's servers')

**Comment by dglazkov** [comment]
Made a ton of progress on this. Remaining items:

- [x] Style it (possibly using https://andybrewer.github.io/mvp/)
- [ ] Couple button and text inputs for easier entry (enter to submit)
