### ISSUE TITLE
Add a debug mode for importers

### ISSUE THREAD

**Issue by dalmaer** [dglazkov/polymath#71]
Let me do a run that outputs the bits but doesn't do the embeddings / library building.

**Comment by PaulKinlan** [comment]
FWIW - I did it here: https://github.com/dglazkov/polymath/pull/86/files#diff-6bac3ad5dcefae4ccd5af67a9693eb21b259100d250ea584bd2bf55670f5fc37R25

**Comment by dalmaer** [comment]
I added a "--debug" and never closed this :/

oh nice, you are using the --debug within the importer too. perfick!
